title: girlbosswords
tagline: a crossword blog by malaika handa
description: a crossword blog by malaika handa
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.girlbosswords.com" # the base hostname & protocol for your site, e.g. http://example.com

author:
  name: Malaika Handa
  url: "https://malaikahanda.com"
  twitter: malisolves

twitter:
  username: malisolves

nav_items:
  - title: about
    url: /about
  - title: email notifs
    url: https://groups.google.com/g/girlbosswords

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-target-blank

permalink: '/puzzle/:title/'

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - data/draw_puzzle.py
